#ifndef __XPFDEF_H__
#define __XPFDEF_H__

enum XPF_CORE_MSG_ID {
    XPF_MSG_ID_QUIT_APP             = 0,
    XPF_MSG_ID_SYS_TRAY_ICON_ACTION = 10,
};

enum XPF_TRAY_ICON_ACTION {
    TRAY_ICON_ACTION_LEFT_CLICKED,
    TRAY_ICON_ACTION_RIGHT_CLICKED,
    TRAY_ICON_ACTION_MIDDLE_CLICKED,
    TRAY_ICON_ACTION_DOUBLE_CLICKED,
};

#endif
