#ifndef XPFTRAYMENUTOPICDEF_H
#define XPFTRAYMENUTOPICDEF_H

static char TOPIC_XPF_TRAYMENU[] = "TOPIC_XPF_TRAYMENU";

namespace XPFTrayMenu {

enum XPF_TRAYMENU_MSG_ID {
    MSG_ID_ICON_ACTION = 10,
};

enum XPF_TRAY_ICON_ACTION {
    TRAY_ICON_ACTION_LEFT_CLICKED,
    TRAY_ICON_ACTION_RIGHT_CLICKED,
    TRAY_ICON_ACTION_MIDDLE_CLICKED,
    TRAY_ICON_ACTION_DOUBLE_CLICKED,
};

typedef struct NNN
{
    bool n;
    NNN() {
        (void)TOPIC_XPF_TRAYMENU;
    }
} NNN;

}

#endif // XPFTRAYMENUTOPICDEF_H
