#ifndef XPFTRAYMENUPLUGINDEFINE_H
#define XPFTRAYMENUPLUGINDEFINE_H

#define PLUGIN_NAME_TRAYMENU "XPFTrayMenu"

namespace XPFTrayMenu {

enum XPF_TRAYMENU_MSG_ID {
    MSG_ID_ICON_ACTION = 10,
};

enum XPF_TRAY_ICON_ACTION {
    TRAY_ICON_ACTION_LEFT_CLICKED,
    TRAY_ICON_ACTION_RIGHT_CLICKED,
    TRAY_ICON_ACTION_MIDDLE_CLICKED,
    TRAY_ICON_ACTION_DOUBLE_CLICKED,
};

}

#endif // XPFTRAYMENUPLUGINDEFINE_H
